apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::862016452072:role/eks_mini3-test-temp-eks-auto-20250108150146488100000003"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      serviceAccountName: app-service-account
      containers:
      - image: public.ecr.aws/g1o9h9r6/mini3/containimage:app2-2
        name: app
        resources: 
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app
status:
  loadBalancer: {}
